services:
  postgres:
    image: postgres:16-alpine
    container_name: sports_booking_postgres
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: sports_booking_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sports_network

volumes:
  pgdata:
    driver: local

networks:
  sports_network:
    driver: bridge
